### PR TITLE
Prevent moving to the top of the page...

### PR DESCRIPTION
**Pull request by Defman21**
If clicked on a link.

### CODE REVIEW

**Comment by Naatan** [comment]
Good idea - but the implementation is not up to standards. JS should be in the actual JS files not mixed in the HTML content. Sorry I can't accept it like this.

**Comment by Defman21** [comment]
Okay, I'll edit this.

**Comment by Defman21** [comment]
So now?

**Comment by Naatan** [comment]
Sorry Defman, that change is too generic to accept - it might affect links that use tooltips adversely - eg. a link that has a tooltip but also a lightbox. You also do not need the `do` keyword there, nor the return.

I think a better/simpler solution would be to simply remove href="#" from those links.

Closing this PR as regardless of the final solution this PR is getting too noisy (too many commits).

**Comment by Defman21** [comment]
Okay. So you'll remove hrefs manually or I can do a pull request again? :smiley:

**Comment by Naatan** [comment]
Up to you. Removing those hrefs is not a priority for me right now (more important things to work on).

**Pull request closed without merging**
